FROM public.ecr.aws/lambda/nodejs:18 as builder

ARG SUBGRAPH_NAME

COPY subgraphs/${SUBGRAPH_NAME} /app
WORKDIR /app
COPY subgraphs/${SUBGRAPH_NAME}/schema.graphql ./
RUN npm run gql
RUN npm run build

FROM public.ecr.aws/lambda/nodejs:18

ARG SUBGRAPH_NAME

WORKDIR /asset
COPY --from=builder /app/package.json /app/package-lock.json ./
COPY --from=builder /app/dist ./dist/
RUN npm install --omit=dev
COPY subgraphs/${SUBGRAPH_NAME}/schema.graphql ./

CMD ["dist/index.handler"]
